spring.application.name=kineo-backend
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/kineodb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=puccampinas
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update